/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Jonathan
 */
public class BosqueDeLasLuciernagas extends javax.swing.JFrame {

    /**
     * Creates new form BosqueDeLasLuciernagas
     */
    public BosqueDeLasLuciernagas() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
        new Espera().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izafiro = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro Game");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izafiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/titulobosquedelasluciernagas.png"))); // NOI18N
        getContentPane().add(izafiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BosqueDeLasLuciernagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BosqueDeLasLuciernagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BosqueDeLasLuciernagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BosqueDeLasLuciernagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BosqueDeLasLuciernagas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel izafiro;
    // End of variables declaration//GEN-END:variables
    
        
    class Espera extends Thread{
       @Override
       public void run()
       {      
         GestorJuego j = GestorJuego.getInstance();
         
         try {
           Thread.sleep(3500);
         } catch (InterruptedException ex) {}       
         
         //j.setEscenarioInicial(0,6);
         //j.setUbicacionInicial(new Point(492,212));
         
         
         JFrame destino = j.getvJF()[j.getEscenarioInicial()[0]][j.getEscenarioInicial()[1]];
         
         for(int i = 0; i<destino.getContentPane().getComponents().length;i++)
         {        
            if(destino.getContentPane().getComponent(i).getAccessibleContext().getAccessibleName().equalsIgnoreCase("tahi"))
            {      
              JLabel l = (JLabel)destino.getContentPane().getComponent(i);  
              j.setUbicacionInicial(l.getLocation());
              break;
            }            
         }         
         
         j.actualizarRecursos(); //Se actualizan cada uno de los recursos
         j.actualizarPuntaje(0);
         
         JFrame[][] vector = j.getvJF();
         dispose();
         
         Tiempo.getInstance(vector).start();       
                  
         try { Thread.sleep(700); } catch (InterruptedException ex) {}
         
         Teclado.getInstace().setPausa(true);  
                  
         GestorJuego.getInstance().setEscenarioActual(vector[GestorJuego.getInstance().getEscenarioInicial()[0]][GestorJuego.getInstance().getEscenarioInicial()[1]]); //Para que los enemigos del escenario inicial empiecen a caminar
         
         vector[j.getEscenarioInicial()[0]][j.getEscenarioInicial()[1]].setVisible(true); 
                  
         Ayuda.getInstance().setVisible(true);         
         Ayuda.getInstance().mostrarMensajes();         
       }     
    }
}
