/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Jacc89
 */
public class CargadorEscenarios1 extends javax.swing.JFrame {

    private JFrame[][] vectorJF;
    
    /**
     * Creates new form CargadorEscenarios
     */
    public CargadorEscenarios1() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage());
        Sonidos.getInstance().activarCursor(this);  
        vectorJF = new JFrame[7][10];        
        new Espera().start();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izafiro = new javax.swing.JLabel();
        cargando = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro Game");
        setMaximumSize(new java.awt.Dimension(530, 320));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izafiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/iZafito-Tittle.png"))); // NOI18N
        getContentPane().add(izafiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        cargando.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cargando.setForeground(new java.awt.Color(255, 255, 255));
        cargando.setText("... Cargando ...");
        getContentPane().add(cargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargadorEscenarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargadorEscenarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargadorEscenarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargadorEscenarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CargadorEscenarios1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargando;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel izafiro;
    // End of variables declaration//GEN-END:variables

    private void prepararEscenarios() {
        
        GestorJuego t = GestorJuego.getInstance(); //Se inician los valores de tahi como salud y propiedades    
        Sonidos.getInstance();
             
        vectorJF[0][0] = new Ventana00_s1();
        vectorJF[0][1] = new Ventana01_s1();
        vectorJF[0][2] = new Ventana02_s1();
        vectorJF[0][3] = new Ventana03_s1();
        vectorJF[0][6] = new Ventana06_s1();
        vectorJF[0][7] = new Ventana07_s1();
        vectorJF[0][8] = new Ventana08_s1();
        vectorJF[1][0] = new Ventana10_s1();
        vectorJF[1][1] = new Ventana11_s1();
        vectorJF[1][2] = new Ventana12_s1();
        vectorJF[1][3] = new Ventana13_s1();
        vectorJF[1][4] = new Ventana14_s1();
        vectorJF[1][5] = new Ventana15_s1();
        vectorJF[1][6] = new Ventana16_s1();
        vectorJF[1][7] = new Ventana17_s1();
        vectorJF[1][8] = new Ventana18_s1();
        vectorJF[2][0] = new Ventana20_s1();
        vectorJF[2][1] = new Ventana21_s1();
        vectorJF[2][2] = new Ventana22_s1();
        vectorJF[2][3] = new Ventana23_s1();
        vectorJF[2][4] = new Ventana24_s1();
        vectorJF[2][5] = new Ventana25_s1();
        vectorJF[2][6] = new Ventana26_s1();
        vectorJF[2][7] = new Ventana27_s1();
        vectorJF[2][8] = new Ventana28_s1();
        vectorJF[2][9] = new Ventana29_s1();
        vectorJF[3][3] = new Ventana33_s1();
        vectorJF[3][8] = new Ventana38_s1();
        vectorJF[3][9] = new Ventana39_s1();
        vectorJF[4][3] = new Ventana43_s1();
        vectorJF[4][6] = new Ventana46_s1();
        vectorJF[5][3] = new Ventana53_s1();
        vectorJF[5][6] = new Ventana56_s1();
        vectorJF[6][3] = new Ventana63_s1();
        vectorJF[6][4] = new Ventana64_s1();
        vectorJF[6][5] = new Ventana65_s1();
        vectorJF[6][6] = new Ventana66_s1();
        
        t.setvJF(vectorJF);              
        
        Ventana00_s1 v00 = (Ventana00_s1)vectorJF[0][0];
        v00.setPosicionVentana(0,0);
        
        Ventana01_s1 v01 = (Ventana01_s1)vectorJF[0][1];
        v01.setPosicionVentana(0,1);
        
        Ventana02_s1 v02 = (Ventana02_s1)vectorJF[0][2];
        v02.setPosicionVentana(0,2);
        
        Ventana03_s1 v03 = (Ventana03_s1)vectorJF[0][3];
        v03.setPosicionVentana(0,3);
        
        Ventana06_s1 v06 = (Ventana06_s1)vectorJF[0][6];
        v06.setPosicionVentana(0,6);
        
        Ventana07_s1 v07 = (Ventana07_s1)vectorJF[0][7];
        v07.setPosicionVentana(0,7);
        
        Ventana08_s1 v08 = (Ventana08_s1)vectorJF[0][8];
        v08.setPosicionVentana(0,8);
        
        Ventana10_s1 v10 = (Ventana10_s1)vectorJF[1][0];
        v10.setPosicionVentana(1,0);
        
        Ventana11_s1 v11 = (Ventana11_s1)vectorJF[1][1];
        v11.setPosicionVentana(1,1);
        
        Ventana12_s1 v12 = (Ventana12_s1)vectorJF[1][2];
        v12.setPosicionVentana(1,2);
        
        Ventana13_s1 v13 = (Ventana13_s1)vectorJF[1][3];
        v13.setPosicionVentana(1,3);
        
        Ventana14_s1 v14 = (Ventana14_s1)vectorJF[1][4];
        v14.setPosicionVentana(1,4);
        
        Ventana15_s1 v15 = (Ventana15_s1)vectorJF[1][5];
        v15.setPosicionVentana(1,5);
        
        Ventana16_s1 v16 = (Ventana16_s1)vectorJF[1][6];
        v16.setPosicionVentana(1,6);
        
        Ventana17_s1 v17 = (Ventana17_s1)vectorJF[1][7];
        v17.setPosicionVentana(1,7);
        
        Ventana18_s1 v18 = (Ventana18_s1)vectorJF[1][8];
        v18.setPosicionVentana(1,8);
        
        Ventana20_s1 v20 = (Ventana20_s1)vectorJF[2][0];
        v20.setPosicionVentana(2,0);
        
        Ventana21_s1 v21 = (Ventana21_s1)vectorJF[2][1];
        v21.setPosicionVentana(2,1);
        
        Ventana22_s1 v22 = (Ventana22_s1)vectorJF[2][2];
        v22.setPosicionVentana(2,2);
        
        Ventana23_s1 v23 = (Ventana23_s1)vectorJF[2][3];
        v23.setPosicionVentana(2,3);
        
        Ventana24_s1 v24 = (Ventana24_s1)vectorJF[2][4];
        v24.setPosicionVentana(2,4);
        
        Ventana25_s1 v25 = (Ventana25_s1)vectorJF[2][5];
        v25.setPosicionVentana(2,5);
        
        Ventana26_s1 v26 = (Ventana26_s1)vectorJF[2][6];
        v26.setPosicionVentana(2,6);
        
        Ventana27_s1 v27 = (Ventana27_s1)vectorJF[2][7];
        v27.setPosicionVentana(2,7);
        
        Ventana28_s1 v28 = (Ventana28_s1)vectorJF[2][8];
        v28.setPosicionVentana(2,8);
        
        Ventana29_s1 v29 = (Ventana29_s1)vectorJF[2][9];
        v29.setPosicionVentana(2,9);
        
        Ventana33_s1 v33 = (Ventana33_s1)vectorJF[3][3];
        v33.setPosicionVentana(3,3);
        
        Ventana38_s1 v38 = (Ventana38_s1)vectorJF[3][8];
        v38.setPosicionVentana(3,8);
        
        Ventana39_s1 v39 = (Ventana39_s1)vectorJF[3][9];
        v39.setPosicionVentana(3,9);
        
        Ventana43_s1 v43 = (Ventana43_s1)vectorJF[4][3];
        v43.setPosicionVentana(4,3);
        
        Ventana46_s1 v46 = (Ventana46_s1)vectorJF[4][6];
        v46.setPosicionVentana(4,6);
        
        Ventana53_s1 v53 = (Ventana53_s1)vectorJF[5][3];
        v53.setPosicionVentana(5,3);
        
        Ventana56_s1 v56 = (Ventana56_s1)vectorJF[5][6];
        v56.setPosicionVentana(5,6);
               
        Ventana63_s1 v63 = (Ventana63_s1)vectorJF[6][3];
        v63.setPosicionVentana(6,3);
        
        Ventana64_s1 v64 = (Ventana64_s1)vectorJF[6][4];
        v64.setPosicionVentana(6,4);
        
        Ventana65_s1 v65 = (Ventana65_s1)vectorJF[6][5];
        v65.setPosicionVentana(6,5);
        
        Ventana66_s1 v66 = (Ventana66_s1)vectorJF[6][6];
        v66.setPosicionVentana(6,6);
        
        
        for (int i = 0; i < vectorJF.length; i++) 
        {
            for (int j = 0; j < vectorJF[i].length; j++)
            {
               if(vectorJF[i][j] != null){
                 vectorJF[i][j].setVisible(true); 
                 vectorJF[i][j].setVisible(false);
               }
            } 
        }
        for (int i = 0; i < vectorJF.length; i++) 
        {
            JLabel jl;
            Icon icon = new ImageIcon (getClass().getResource("imagenes/personajes/tahi/"+GestorJuego.getInstance().getGenero()+"2.png"));
            for (int j = 0; j < vectorJF[i].length; j++)
            {
               if(vectorJF[i][j] != null){
                 for(int k = 0; k<vectorJF[i][j].getContentPane().getComponents().length;k++)
                  {        
                    if(vectorJF[i][j].getContentPane().getComponent(k).getAccessibleContext().getAccessibleName().equalsIgnoreCase("tahi"))
                    {
                       jl = (JLabel)vectorJF[i][j].getContentPane().getComponent(k);
                       jl.setIcon(icon);                       
                    }                     
                  } 
               }
            } 
        }
    }
    
    
    
    public class Espera extends Thread
    {        
        @Override
        public void run()
        {
           prepararEscenarios(); 
           try {
             Thread.sleep(1);
           } catch (InterruptedException ex) {
             Logger.getLogger(CargadorEscenarios1.class.getName()).log(Level.SEVERE, null, ex);
           }
           setVisible(false);
           dispose(); 
           
           // SE MUESTRA LA PRIMERA ESCENA, AQUI COMIENZA EL JUEGO COMO TAL.           
           new BosqueDeLasLuciernagas().setVisible(true);
           Tiempo.getInstance(vectorJF);
        }      
    }   
}