/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class ContinuarPartida2 extends javax.swing.JFrame {

    /**
     * Creates new form ContinuarPartida2
     */
    public ContinuarPartida2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
        
        mensaje.setText("¡Hola "+GestorJuego.getInstance().getUsuario()+"!, ¿qué deseas hacer ahora?");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        gaviotas = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        gaviotas1 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        continuar = new javax.swing.JLabel();
        jugarPuzzle = new javax.swing.JLabel();
        cuadro = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        fondocuadro = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro - Continuar Partida");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/iZafito-Tittle-80.png"))); // NOI18N
        titulo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 17, -1, 42));

        gaviotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(gaviotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 63));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/iZafito-Tittle-80.png"))); // NOI18N
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 59, -1, 60));

        gaviotas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(gaviotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        mensaje.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Hola NombreUsuario, ¿qué deseas hacer ahora?");
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 145, 640, -1));

        continuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/continuar-partida.png"))); // NOI18N
        continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continuarMouseExited(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 195, -1, -1));

        jugarPuzzle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/juegospuzzle.png"))); // NOI18N
        jugarPuzzle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarPuzzleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jugarPuzzleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jugarPuzzleMouseExited(evt);
            }
        });
        getContentPane().add(jugarPuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 235, -1, -1));

        cuadro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/creditos/efectodescripcion/fondocreditosmusica.png"))); // NOI18N
        cuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 185, 180, 100));

        atras.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("Atrás");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasMouseExited(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 40));

        fondocuadro.setForeground(new java.awt.Color(255, 255, 255));
        fondocuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/creditos/efectodescripcion/fondocreditosmusica.png"))); // NOI18N
        fondocuadro.setText("Hola");
        fondocuadro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fondocuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(fondocuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 125, 520, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/fondoportada.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseClicked
        // TODO add your handling code here:
        
        GestorJuego.getInstance().setSesionIniciada(true);
        
        Sonidos.getInstance().detener("portada");
        Sonidos.getInstance().detener("sonidosbosque");
        Sonidos.getInstance().detener("creditos");
        Sonidos.getInstance().detener("boton");
        
        this.setVisible(false);
        this.dispose();
        this.removeAll();
        
        new CargadorEscenarios1().setVisible(true);
    }//GEN-LAST:event_continuarMouseClicked

    private void continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseEntered
        // TODO add your handling code here:
        this.continuar.setIcon(new ImageIcon (getClass().getResource("texto/portada/continuar-partida-over.png")));
        Sonidos.getInstance().reproducir("boton");
    }//GEN-LAST:event_continuarMouseEntered

    private void continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseExited
        // TODO add your handling code here:
        this.continuar.setIcon(new ImageIcon (getClass().getResource("texto/portada/continuar-partida.png")));
    }//GEN-LAST:event_continuarMouseExited

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        removeAll();

        new ContinuarPartida().setVisible(true);
    }//GEN-LAST:event_atrasMouseClicked

    private void atrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseExited
        // TODO add your handling code here:
        atras.setForeground(Color.white);
    }//GEN-LAST:event_atrasMouseExited

    private void atrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseEntered
        // TODO add your handling code here:
        Sonidos.getInstance().reproducir("boton");
        atras.setForeground(Color.cyan);
    }//GEN-LAST:event_atrasMouseEntered

    private void jugarPuzzleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarPuzzleMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        removeAll();
        
        new JuegosPuzzle().setVisible(true);
    }//GEN-LAST:event_jugarPuzzleMouseClicked

    private void jugarPuzzleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarPuzzleMouseEntered
        // TODO add your handling code here:
        Sonidos.getInstance().reproducir("boton");
        this.jugarPuzzle.setIcon(new ImageIcon (getClass().getResource("texto/portada/juegospuzzle-over.png")));
    }//GEN-LAST:event_jugarPuzzleMouseEntered

    private void jugarPuzzleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarPuzzleMouseExited
        // TODO add your handling code here:
        this.jugarPuzzle.setIcon(new ImageIcon (getClass().getResource("texto/portada/juegospuzzle.png")));
    }//GEN-LAST:event_jugarPuzzleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContinuarPartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContinuarPartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContinuarPartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContinuarPartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContinuarPartida2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras;
    private javax.swing.JLabel continuar;
    private javax.swing.JLabel cuadro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondocuadro;
    private javax.swing.JLabel gaviotas;
    private javax.swing.JLabel gaviotas1;
    private javax.swing.JLabel jugarPuzzle;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
