/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class CreditosMusica extends javax.swing.JFrame {

    /**
     * Creates new form CrearPartida
     */
    public CreditosMusica() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
    
        this.texto1.setText("[Menú Principal] The Saga Begins - Celestial Aeon Project");                           
        this.texto2.setText("[Historia] Good Memories - Aaron Krogh");
        this.texto3.setText("[Bosque, día] Hamlet - RMN Music Pack (Lana42)");
        this.texto4.setText("[Bosque, noche] Meadow of the Past - Joel Day");
        this.texto5.setText("[Jardín de las Fuentes] Village - Joel Day");
        this.texto6.setText("[Puzzles 1] Who Left The Milk Out - Aaron Krogh");
        this.texto7.setText("[Puzzles 2] Fire Drill - Aaron Krogh");
        this.texto8.setText("[Jefe Final] Megaboss - Aaron Krogh");
        this.texto9.setText("[Refugio del Patriarca] Pre-Boss Battle Tension - Aaron Krogh");
        this.texto10.setText("[Créditos] Centaur's Theme - Steve O'Brien");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        gaviotas1 = new javax.swing.JLabel();
        gaviotas = new javax.swing.JLabel();
        texto10 = new javax.swing.JLabel();
        texto9 = new javax.swing.JLabel();
        texto8 = new javax.swing.JLabel();
        texto7 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        fondocuadro = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro - Créditos de la Música");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/izafitotittlepequeno.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        atras.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("Atrás");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasMouseExited(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 90, 40));

        gaviotas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(gaviotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        gaviotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(gaviotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 63));

        texto10.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto10.setForeground(new java.awt.Color(255, 255, 255));
        texto10.setText("...");
        texto10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto10MouseExited(evt);
            }
        });
        getContentPane().add(texto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 500, -1));

        texto9.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto9.setForeground(new java.awt.Color(255, 255, 255));
        texto9.setText("...");
        texto9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto9MouseExited(evt);
            }
        });
        getContentPane().add(texto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 500, -1));

        texto8.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto8.setForeground(new java.awt.Color(255, 255, 255));
        texto8.setText("...");
        texto8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto8MouseExited(evt);
            }
        });
        getContentPane().add(texto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 500, -1));

        texto7.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto7.setForeground(new java.awt.Color(255, 255, 255));
        texto7.setText("...");
        texto7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto7MouseExited(evt);
            }
        });
        getContentPane().add(texto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 500, -1));

        texto6.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto6.setForeground(new java.awt.Color(255, 255, 255));
        texto6.setText("...");
        texto6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto6MouseExited(evt);
            }
        });
        getContentPane().add(texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 500, -1));

        texto5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto5.setForeground(new java.awt.Color(255, 255, 255));
        texto5.setText("...");
        texto5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto5MouseExited(evt);
            }
        });
        getContentPane().add(texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 500, -1));

        texto4.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto4.setForeground(new java.awt.Color(255, 255, 255));
        texto4.setText("...");
        texto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto4MouseExited(evt);
            }
        });
        getContentPane().add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 500, -1));

        texto3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 255, 255));
        texto3.setText("...");
        texto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto3MouseExited(evt);
            }
        });
        getContentPane().add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 500, -1));

        texto2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.setText("...");
        texto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto2MouseExited(evt);
            }
        });
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 500, -1));

        texto1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.setText("...");
        texto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto1MouseExited(evt);
            }
        });
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 500, -1));

        fondocuadro.setForeground(new java.awt.Color(255, 255, 255));
        fondocuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/creditos/efectodescripcion/fondocreditosmusica.png"))); // NOI18N
        fondocuadro.setText("Hola");
        fondocuadro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fondocuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(fondocuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 520, 215));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/fondoportada.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        removeAll();
        
        try {
            new MainMenu().setVisible(true);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(CreditosMusica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atrasMouseClicked

    private void atrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseExited
        // TODO add your handling code here:
        atras.setForeground(Color.white);
    }//GEN-LAST:event_atrasMouseExited

    private void atrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseEntered
        // TODO add your handling code here:
        Sonidos.getInstance().reproducir("boton");
        atras.setForeground(Color.cyan);      
    }//GEN-LAST:event_atrasMouseEntered

    private void texto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto1MouseClicked
        // TODO add your handling code here:        
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.jamendo.com/en/track/585840/the-saga-begins"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto1MouseClicked

    private void texto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://soundcloud.com/aaron-anderson-11/301-good-memories-scene-mp3"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto2MouseClicked

    private void texto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto3MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("http://rpgmaker.net/musicpack/"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto3MouseClicked

    private void texto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto4MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("http://blog.dayjo.org/free-rpg-music-pack-part-1/"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto4MouseClicked

    private void texto5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto5MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("http://blog.dayjo.org/free-rpg-music-pack-part-1/"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto5MouseClicked

    private void texto6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto6MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://soundcloud.com/aaron-anderson-11/who-left-the-milk-out"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto6MouseClicked

    private void texto7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto7MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://soundcloud.com/aaron-anderson-11/293-a-fire-drill-loop-ogg"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto7MouseClicked

    private void texto8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto8MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://soundcloud.com/aaron-anderson-11/b-2-2-megaboss"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto8MouseClicked

    private void texto9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto9MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://soundcloud.com/aaron-anderson-11/162-a-pre-boss-battle-tension"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto9MouseClicked

    private void texto10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto10MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://soundcloud.com/stevenobrien/centaurs-theme-2010"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_texto10MouseClicked

    private void texto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto1MouseEntered
        // TODO add your handling code here:
        texto1.setForeground(Color.cyan);
    }//GEN-LAST:event_texto1MouseEntered

    private void texto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto1MouseExited
        // TODO add your handling code here:
        texto1.setForeground(Color.white);
    }//GEN-LAST:event_texto1MouseExited

    private void texto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseEntered
        // TODO add your handling code here:
        texto2.setForeground(Color.cyan);
    }//GEN-LAST:event_texto2MouseEntered

    private void texto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto2MouseExited
        // TODO add your handling code here:
        texto2.setForeground(Color.white);
    }//GEN-LAST:event_texto2MouseExited

    private void texto3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto3MouseEntered
        // TODO add your handling code here:
        texto3.setForeground(Color.cyan);
    }//GEN-LAST:event_texto3MouseEntered

    private void texto3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto3MouseExited
        // TODO add your handling code here:
        texto3.setForeground(Color.white);        
    }//GEN-LAST:event_texto3MouseExited

    private void texto4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto4MouseEntered
        // TODO add your handling code here:
        texto4.setForeground(Color.cyan);
    }//GEN-LAST:event_texto4MouseEntered

    private void texto4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto4MouseExited
        // TODO add your handling code here:
        texto4.setForeground(Color.white);
    }//GEN-LAST:event_texto4MouseExited

    private void texto5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto5MouseEntered
        // TODO add your handling code here:
        texto5.setForeground(Color.cyan);
    }//GEN-LAST:event_texto5MouseEntered

    private void texto5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto5MouseExited
        // TODO add your handling code here:
        texto5.setForeground(Color.white);
    }//GEN-LAST:event_texto5MouseExited

    private void texto6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto6MouseEntered
        // TODO add your handling code here:
        texto6.setForeground(Color.cyan);
    }//GEN-LAST:event_texto6MouseEntered

    private void texto6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto6MouseExited
        // TODO add your handling code here:
        texto6.setForeground(Color.white);
    }//GEN-LAST:event_texto6MouseExited

    private void texto7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto7MouseEntered
        // TODO add your handling code here:
        texto7.setForeground(Color.cyan);
    }//GEN-LAST:event_texto7MouseEntered

    private void texto7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto7MouseExited
        // TODO add your handling code here:
        texto7.setForeground(Color.white);
    }//GEN-LAST:event_texto7MouseExited

    private void texto8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto8MouseEntered
        // TODO add your handling code here:
        texto8.setForeground(Color.cyan);
    }//GEN-LAST:event_texto8MouseEntered

    private void texto8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto8MouseExited
        // TODO add your handling code here:
        texto8.setForeground(Color.white);
    }//GEN-LAST:event_texto8MouseExited

    private void texto9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto9MouseEntered
        // TODO add your handling code here:
        texto9.setForeground(Color.cyan);
    }//GEN-LAST:event_texto9MouseEntered

    private void texto9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto9MouseExited
        // TODO add your handling code here:
        texto9.setForeground(Color.white);
    }//GEN-LAST:event_texto9MouseExited

    private void texto10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto10MouseEntered
        // TODO add your handling code here:
        texto10.setForeground(Color.cyan);
    }//GEN-LAST:event_texto10MouseEntered

    private void texto10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto10MouseExited
        // TODO add your handling code here:
        texto10.setForeground(Color.white);
    }//GEN-LAST:event_texto10MouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CreditosMusica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondocuadro;
    private javax.swing.JLabel gaviotas;
    private javax.swing.JLabel gaviotas1;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto10;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto8;
    private javax.swing.JLabel texto9;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
