/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class DatosConexion extends javax.swing.JFrame {

    /**
     * Creates new form CrearPartida
     */
    public DatosConexion() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        confirmar = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        gaviotas1 = new javax.swing.JLabel();
        gaviotas = new javax.swing.JLabel();
        servidorLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        servidorCampo = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        passwordCampo = new javax.swing.JTextField();
        userNameCampo = new javax.swing.JTextField();
        nota = new javax.swing.JLabel();
        fondocuadro = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro - Datos Conexión Remota");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/izafitotittlepequeno.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        confirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        confirmar.setForeground(new java.awt.Color(255, 255, 255));
        confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmar.setText("O K");
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmarMouseExited(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 90, 40));

        atras.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("Cancelar");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasMouseExited(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, 40));

        gaviotas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(gaviotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        gaviotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(gaviotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 63));

        servidorLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        servidorLabel.setForeground(new java.awt.Color(255, 255, 255));
        servidorLabel.setText("Servidor:");
        getContentPane().add(servidorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Contraseña:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        servidorCampo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        servidorCampo.setForeground(new java.awt.Color(0, 102, 204));
        servidorCampo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        servidorCampo.setText("jdbc:oracle:thin:@orion.javeriana.edu.co:1521:PUJDISOR");
        getContentPane().add(servidorCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 245, 170, 30));

        userNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("Usuario:");
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        passwordCampo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        passwordCampo.setForeground(new java.awt.Color(0, 102, 204));
        passwordCampo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(passwordCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 195, 170, 30));

        userNameCampo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        userNameCampo.setForeground(new java.awt.Color(0, 102, 204));
        userNameCampo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userNameCampo.setText("CIS1310IS08");
        getContentPane().add(userNameCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 145, 170, 30));

        nota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nota.setForeground(java.awt.Color.cyan);
        nota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota.setText("Datos de Conexión Remota");
        getContentPane().add(nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 638, -1));

        fondocuadro.setForeground(new java.awt.Color(255, 255, 255));
        fondocuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/creditos/efectodescripcion/fondocreditosmusica.png"))); // NOI18N
        fondocuadro.setText("Hola");
        fondocuadro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fondocuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(fondocuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 520, 215));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/fondoportada.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        removeAll();
        
        try {
            new MainMenu().setVisible(true);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(DatosConexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atrasMouseClicked

    private void atrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseExited
        // TODO add your handling code here:
        atras.setForeground(Color.white);
    }//GEN-LAST:event_atrasMouseExited

    private void atrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseEntered
        // TODO add your handling code here:
        Sonidos.getInstance().reproducir("boton");
        atras.setForeground(Color.cyan);      
    }//GEN-LAST:event_atrasMouseEntered

    private void confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseClicked
        // TODO add your handling code here:
        Conexion.usernameConnection = userNameCampo.getText();
        Conexion.passwordConnection = passwordCampo.getText();
        Conexion.serverConnection = servidorCampo.getText();
                
        setVisible(false);
        dispose();
        removeAll();
        
        try {
            new MainMenu().setVisible(true);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(DatosConexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmarMouseClicked

    private void confirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseEntered
        // TODO add your handling code here:
        Sonidos.getInstance().reproducir("boton");
        confirmar.setForeground(Color.cyan); 
    }//GEN-LAST:event_confirmarMouseEntered

    private void confirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseExited
        // TODO add your handling code here:
        confirmar.setForeground(Color.white);
    }//GEN-LAST:event_confirmarMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DatosConexion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras;
    private javax.swing.JLabel confirmar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondocuadro;
    private javax.swing.JLabel gaviotas;
    private javax.swing.JLabel gaviotas1;
    private javax.swing.JLabel nota;
    private javax.swing.JTextField passwordCampo;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField servidorCampo;
    private javax.swing.JLabel servidorLabel;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField userNameCampo;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
