/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public final class JuegosPuzzle extends javax.swing.JFrame {

    private int numPuzzle = 1;
    private int totalPuzzles = 0;
    private Icon[] imagenesPuzzle;
    private String[] titulos;
    private String[] descripciones;
    
    /**
     * Creates new form JuegosPuzzle
     */
    public JuegosPuzzle() {
        initComponents();
        this.setLocationRelativeTo(null); this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
        
        imagenesPuzzle = new Icon[7];
        imagenesPuzzle[0] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/1.png"));
        imagenesPuzzle[1] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/2.png"));
        imagenesPuzzle[2] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/3.png"));
        imagenesPuzzle[3] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/4.png"));
        imagenesPuzzle[4] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/5.png"));
        imagenesPuzzle[5] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/6.png"));
        imagenesPuzzle[6] = new ImageIcon (getClass().getResource("imagenes/puzzle/iconos/7.png"));
        
        titulos = new String[7];
        titulos[0] = "¡Topos en La Cosecha!";
        titulos[1] = "Cima del Trueno";
        titulos[2] = "¡A cortar Madera!";
        titulos[3] = "¡Encuentra la Pareja!";
        titulos[4] = "¡Ranas en El Estanque!";
        titulos[5] = "La Gran Cascada";
        titulos[6] = "¡No dejes que te vean!";
        
        descripciones = new String[7];
        descripciones[0] = "Concepto de Fracción 1";
        descripciones[1] = "Concepto de Fracción 2";
        descripciones[2] = "Concepto de Fracción 3";
        descripciones[3] = "Operaciones con Fracciones";
        descripciones[4] = "Tipos de Fracciones";
        descripciones[5] = "Fracciones Mixtas";
        descripciones[6] = "Fracciones Equivalentes";
        
        cargarPuzzles();
        
        if(totalPuzzles > 0)
        {
          this.imagenPuzzle.setIcon(imagenesPuzzle[0]);  
          this.nombrePuzzle.setText(titulos[0]);
          this.descripcionPuzzle.setText(descripciones[0]);          
        }
    }
    
    public void cargarPuzzles()
    {
        if(GestorJuego.getInstance().getRecursos()[5])
        {
          totalPuzzles = 7;  
        }
        else if(GestorJuego.getInstance().getRecursos()[4])
        { 
          totalPuzzles = 6;  
        }
        else if((GestorJuego.getInstance().getRecursos()[0] && GestorJuego.getInstance().getPuertas()[1] && GestorJuego.getInstance().getRecursos()[2])
                 || GestorJuego.getInstance().getPuertas()[3])
        {  
          totalPuzzles = 5;  
        }
        else if((GestorJuego.getInstance().getRecursos()[0] && GestorJuego.getInstance().getRecursos()[2])
                 || GestorJuego.getInstance().getPuertas()[1])
        {  
          totalPuzzles = 4;  
        }
        else if(GestorJuego.getInstance().getRecursos()[0])
        {
          totalPuzzles = 2;  
        }
        else if(GestorJuego.getInstance().getRecursos()[1])
        { 
          totalPuzzles = 1;  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPuzzle = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        anterior = new javax.swing.JLabel();
        siguiente = new javax.swing.JLabel();
        descripcionPuzzle = new javax.swing.JLabel();
        nombrePuzzle = new javax.swing.JLabel();
        jugar = new javax.swing.JToggleButton();
        atras = new javax.swing.JLabel();
        gaviotas = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro - Juegos Puzzle");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPuzzle.setBackground(new java.awt.Color(0, 0, 0));
        imagenPuzzle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenPuzzle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/puzzle/puzzle4/interrogacion.png"))); // NOI18N
        imagenPuzzle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        imagenPuzzle.setOpaque(true);
        getContentPane().add(imagenPuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 200));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/izafitotittlepequeno.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        anterior.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        anterior.setForeground(new java.awt.Color(255, 255, 255));
        anterior.setText("<");
        anterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anteriorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anteriorMouseExited(evt);
            }
        });
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 285, -1, -1));

        siguiente.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        siguiente.setForeground(new java.awt.Color(255, 255, 255));
        siguiente.setText(">");
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siguienteMouseExited(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 285, -1, -1));

        descripcionPuzzle.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        descripcionPuzzle.setForeground(new java.awt.Color(255, 255, 255));
        descripcionPuzzle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descripcionPuzzle.setText("Texto de Prueba 2");
        getContentPane().add(descripcionPuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 230, -1));

        nombrePuzzle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombrePuzzle.setForeground(new java.awt.Color(0, 0, 204));
        nombrePuzzle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombrePuzzle.setText("Texto de Prueba 1");
        getContentPane().add(nombrePuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 250, -1));

        jugar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jugar.setForeground(new java.awt.Color(0, 0, 204));
        jugar.setText("¡Jugar!");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        atras.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("Volver");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasMouseExited(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 90, 40));

        gaviotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        getContentPane().add(gaviotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/fondoportada.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        // TODO add your handling code here:
        if(numPuzzle < totalPuzzles)
        {
           Sonidos.getInstance().reproducir("boton"); 
           numPuzzle++;
           this.imagenPuzzle.setIcon(imagenesPuzzle[numPuzzle-1]);
           this.nombrePuzzle.setText(titulos[numPuzzle-1]);
           this.descripcionPuzzle.setText(descripciones[numPuzzle-1]);
        }
    }//GEN-LAST:event_siguienteMouseClicked

    private void siguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseEntered
        // TODO add your handling code here:
        siguiente.setForeground(Color.cyan);
    }//GEN-LAST:event_siguienteMouseEntered

    private void siguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseExited
        // TODO add your handling code here:
        siguiente.setForeground(Color.white);
    }//GEN-LAST:event_siguienteMouseExited

    private void anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorMouseClicked
        // TODO add your handling code here:
        if(numPuzzle >= 2)
        {
           Sonidos.getInstance().reproducir("boton"); 
           numPuzzle--;
           this.imagenPuzzle.setIcon(imagenesPuzzle[numPuzzle-1]);
           this.nombrePuzzle.setText(titulos[numPuzzle-1]);
           this.descripcionPuzzle.setText(descripciones[numPuzzle-1]);
        }
    }//GEN-LAST:event_anteriorMouseClicked

    private void anteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorMouseEntered
        // TODO add your handling code here:
        anterior.setForeground(Color.cyan);
    }//GEN-LAST:event_anteriorMouseEntered

    private void anteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorMouseExited
        // TODO add your handling code here:
        anterior.setForeground(Color.white);
    }//GEN-LAST:event_anteriorMouseExited

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        // TODO add your handling code here:
        totalPuzzles = 0;
        setVisible(false);
        dispose();
        removeAll();

        new ContinuarPartida2().setVisible(true);       
    }//GEN-LAST:event_atrasMouseClicked

    private void atrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseExited
        // TODO add your handling code here:
        atras.setForeground(Color.white);
    }//GEN-LAST:event_atrasMouseExited

    private void atrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseEntered
        // TODO add your handling code here:
        Sonidos.getInstance().reproducir("boton");
        atras.setForeground(Color.cyan);
    }//GEN-LAST:event_atrasMouseEntered

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        if(totalPuzzles == 0)
        {
          Sonidos.getInstance().reproducir("error");  
          JOptionPane.showMessageDialog(null, "¡Aún no hay Juegos habilitados!");  
        }
        else
        {
          this.setVisible(false);
          this.dispose();
          this.removeAll();
        
          Sonidos.getInstance().detener("portada");
          Sonidos.getInstance().detener("sonidosbosque");
          PruebaPuzzle.getInstance().abrirActividad(numPuzzle, null, null);
        }
    }//GEN-LAST:event_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegosPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegosPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegosPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegosPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JuegosPuzzle().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anterior;
    private javax.swing.JLabel atras;
    private javax.swing.JLabel descripcionPuzzle;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel gaviotas;
    private javax.swing.JLabel imagenPuzzle;
    private javax.swing.JToggleButton jugar;
    private javax.swing.JLabel nombrePuzzle;
    private javax.swing.JLabel siguiente;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
