/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacc89
 */
public class MainMenu extends javax.swing.JFrame {

        
    /**
     * Creates new form IniciarJuego
     */
    public MainMenu() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
        Sonidos.getInstance().activarCursor(this);
        GestorJuego.setPartida(null); //Elimina toda instancia de alguna cuenta cargada inicialmente.        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciar = new javax.swing.JLabel();
        continuar = new javax.swing.JLabel();
        creditos = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gaviotas = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        cuadro = new javax.swing.JLabel();
        datosConexionLabel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro Game");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/iniciar-partida.png"))); // NOI18N
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarMouseExited(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 176, -1, 25));

        continuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/continuar-partida.png"))); // NOI18N
        continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continuarMouseExited(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 206, -1, 25));

        creditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/creditos.png"))); // NOI18N
        creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditosMouseExited(evt);
            }
        });
        getContentPane().add(creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 236, -1, 25));

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/salir.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 266, -1, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Famitsu Characters");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Créditos Música");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jacc Company, Inc.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RPG Maker XP Graphics");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("January, 2014");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 310, 100, -1));

        gaviotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        getContentPane().add(gaviotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/iZafito-Tittle2.png"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 33, -1, -1));

        cuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/creditos/efectodescripcion/fondocreditosmusica.png"))); // NOI18N
        cuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 168, 190, 130));

        datosConexionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datosConexionLabelMouseClicked(evt);
            }
        });
        getContentPane().add(datosConexionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 60, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/fondoportada.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:         
        Sonidos.getInstance().detener("boton");
        Sonidos.getInstance().detener("portada");
        Sonidos.getInstance().detener("sonidosbosque");
        this.setVisible(false);
        this.dispose();
        new Historia().setVisible(true);
    }//GEN-LAST:event_iniciarMouseClicked

    private void iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseEntered
        // TODO add your handling code here:
        this.iniciar.setIcon(new ImageIcon (getClass().getResource("texto/portada/iniciar-partida-over.png")));
        Sonidos.getInstance().reproducir("boton");        
    }//GEN-LAST:event_iniciarMouseEntered

    private void iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseExited
        // TODO add your handling code here:
        this.iniciar.setIcon(new ImageIcon (getClass().getResource("texto/portada/iniciar-partida.png")));
    }//GEN-LAST:event_iniciarMouseExited

    private void continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseEntered
        // TODO add your handling code here:
        this.continuar.setIcon(new ImageIcon (getClass().getResource("texto/portada/continuar-partida-over.png")));
        Sonidos.getInstance().reproducir("boton");        
    }//GEN-LAST:event_continuarMouseEntered

    private void continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseExited
        // TODO add your handling code here:
        this.continuar.setIcon(new ImageIcon (getClass().getResource("texto/portada/continuar-partida.png")));
    }//GEN-LAST:event_continuarMouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
                
        if(JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir de iZafiro?", "Seleccionar una Opción", JOptionPane.YES_NO_OPTION) == 0)
        {
          Sonidos.getInstance().detener("portada");
          Sonidos.getInstance().detener("sonidosbosque");
          
          this.setVisible(false);
          this.dispose();
          
          System.exit(0);
        }
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        // TODO add your handling code here:
       this.salir.setIcon(new ImageIcon (getClass().getResource("texto/portada/salir-over.png")));
       Sonidos.getInstance().reproducir("boton");
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        // TODO add your handling code here:
        this.salir.setIcon(new ImageIcon (getClass().getResource("texto/portada/salir.png")));
    }//GEN-LAST:event_salirMouseExited

    private void creditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosMouseEntered
        // TODO add your handling code here:
        this.creditos.setIcon(new ImageIcon (getClass().getResource("texto/portada/creditos-over.png")));
        Sonidos.getInstance().reproducir("boton");
    }//GEN-LAST:event_creditosMouseEntered

    private void creditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosMouseExited
        // TODO add your handling code here:
        this.creditos.setIcon(new ImageIcon (getClass().getResource("texto/portada/creditos.png")));
    }//GEN-LAST:event_creditosMouseExited

    private void creditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosMouseClicked
        // TODO add your handling code here:  
        Sonidos.getInstance().detener("portada");
        Sonidos.getInstance().detener("sonidosbosque");
        this.setVisible(false);
        this.dispose();
        new Creditos().setVisible(true);
    }//GEN-LAST:event_creditosMouseClicked

    private void continuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseClicked
        // TODO add your handling code here:
        Sonidos.getInstance().detener("boton");
        this.setVisible(false);
        this.dispose();
        new ContinuarPartida().setVisible(true);
    }//GEN-LAST:event_continuarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new CreditosMusica().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(Color.cyan);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4MouseExited

    private void datosConexionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosConexionLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new DatosConexion().setVisible(true);
    }//GEN-LAST:event_datosConexionLabelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("http://www.rpgmakerweb.com/products/programs/rpg-maker-xp"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("http://www.famitsu.com/freegame/tool/chibi/index1.html"));
                }
            }
        } catch (Exception e) {
        }        
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new MainMenu().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel continuar;
    private javax.swing.JLabel creditos;
    private javax.swing.JLabel cuadro;
    private javax.swing.JLabel datosConexionLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel gaviotas;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}