/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class Pausa extends javax.swing.JFrame {

    private static Pausa p = null;
    
    /**
     * Creates new form Pausa
     */
    public Pausa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
    }
    
    public static Pausa getInstance()
    {
      if(p == null) { p = new Pausa(); }
      return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reanudar = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pausa");
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reanudar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reanudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/botones/reanudar-btn.png"))); // NOI18N
        reanudar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reanudarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reanudarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reanudarMouseExited(evt);
            }
        });
        getContentPane().add(reanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 144, 30));

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/texto/portada/salir.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 144, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/pausa.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reanudarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reanudarMouseClicked
        // TODO add your handling code here:
        if(Teclado.getInstace().isMusica()){
            Sonidos.getInstance().reproducirLoop(Tiempo.getInstance(null).getSonidoActual());
        }
        this.reanudar.setIcon(new ImageIcon (getClass().getResource("imagenes/botones/reanudar-btn.png")));
        Teclado.getInstace().setPausa(false);
        this.dispose();
    }//GEN-LAST:event_reanudarMouseClicked

    private void reanudarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reanudarMouseEntered
        // TODO add your handling code here:
        this.reanudar.setIcon(new ImageIcon (getClass().getResource("imagenes/botones/reanudar-btn-over.png")));
        Sonidos.getInstance().reproducir("boton");
    }//GEN-LAST:event_reanudarMouseEntered

    private void reanudarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reanudarMouseExited
        // TODO add your handling code here:
        this.reanudar.setIcon(new ImageIcon (getClass().getResource("imagenes/botones/reanudar-btn.png")));
    }//GEN-LAST:event_reanudarMouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
                
        this.setAlwaysOnTop(false);
        
        if(JOptionPane.showConfirmDialog(null, "¿Seguro que quieres salir del Juego?", "Seleccionar una Opción", JOptionPane.YES_NO_OPTION) == 0)
        {
            //GUARDAR PARTIDAAAAAAAA

            AdministradorConsultasSQL ad = new AdministradorConsultasSQL();
            ad.guardarPartida();

            this.setVisible(false);
            this.dispose();

            Teclado.getInstace().setPausa(false);
            GestorJuego.getInstance().cerrarPartida();

            try {
                new TablaPuntaje3().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Pausa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.setAlwaysOnTop(true);
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        // TODO add your handling code here:
        this.salir.setIcon(new ImageIcon (getClass().getResource("texto/portada/salir-over.png")));
        Sonidos.getInstance().reproducir("boton");
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        // TODO add your handling code here:
        this.salir.setIcon(new ImageIcon (getClass().getResource("texto/portada/salir.png")));
    }//GEN-LAST:event_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Pausa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel reanudar;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
