/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class Puzzle7_4 extends javax.swing.JFrame {

    
    private String personaje = GestorJuego.getInstance().getGenero();
    
    /**
     * Creates new form Puzzle7_4
     */
    public Puzzle7_4() {
        initComponents();
        this.setLocationRelativeTo(null); this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
               
        tahi.setIcon(new ImageIcon (getClass().getResource("imagenes/personajes/tahi/"+personaje+"11.png")));
        
        tahi.setLocation(tahi.getLocation().x, 550);
                
        Sonidos.getInstance().reproducirLoop("rio");
        Sonidos.getInstance().reproducirLoop("entradaaldea");
        
        new Movimiento().start();
    }
    
    
    public void cerrarVentana()
    {
       Sonidos.getInstance().detener("rio");
       Sonidos.getInstance().detener("entradaaldea");
       this.setVisible(false);
       this.dispose();
       Sonidos.getInstance().reproducirLoop(Tiempo.getInstance(null).getSonidoActual());
       GestorJuego.getInstance().getvJF()[3][3].setVisible(true);
       PruebaPuzzle.getInstance().setActivado(false);
       
       this.removeAll();
          
       try {
           this.finalize();
       } catch (Throwable ex) {
          Logger.getLogger(Puzzle7_4.class.getName()).log(Level.SEVERE, null, ex);
       }

       System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fuente1 = new javax.swing.JLabel();
        fuente2 = new javax.swing.JLabel();
        fuente3 = new javax.swing.JLabel();
        fuente4 = new javax.swing.JLabel();
        fuente5 = new javax.swing.JLabel();
        fuente6 = new javax.swing.JLabel();
        objeto1 = new javax.swing.JLabel();
        tahi = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro - Salida del Jardín de Las Fuentes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fuente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/fuente.gif"))); // NOI18N
        getContentPane().add(fuente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 314, -1, -1));

        fuente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/fuente.gif"))); // NOI18N
        getContentPane().add(fuente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 214, -1, -1));

        fuente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/fuente.gif"))); // NOI18N
        getContentPane().add(fuente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 114, -1, -1));

        fuente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/fuente.gif"))); // NOI18N
        getContentPane().add(fuente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 314, -1, -1));

        fuente5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/fuente.gif"))); // NOI18N
        getContentPane().add(fuente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 114, -1, -1));

        fuente6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/fuente.gif"))); // NOI18N
        getContentPane().add(fuente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 214, -1, -1));

        objeto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/marco1.png"))); // NOI18N
        objeto1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(objeto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 0, -1, 70));

        tahi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/personajes/tahi/tahi11.png"))); // NOI18N
        getContentPane().add(tahi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/puzzle/puzzle7/7-4.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puzzle7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puzzle7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puzzle7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puzzle7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Puzzle7_4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fuente1;
    private javax.swing.JLabel fuente2;
    private javax.swing.JLabel fuente3;
    private javax.swing.JLabel fuente4;
    private javax.swing.JLabel fuente5;
    private javax.swing.JLabel fuente6;
    private javax.swing.JLabel objeto1;
    private javax.swing.JLabel tahi;
    // End of variables declaration//GEN-END:variables

    
    public class Movimiento extends Thread
    {
       @Override
       public void run()
       {
          Icon corriendo = new ImageIcon (getClass().getResource("imagenes/puzzle/puzzle2/"+personaje+"/4.gif"));
          Icon detenido = new ImageIcon (getClass().getResource("imagenes/personajes/tahi/"+personaje+"2.png"));
          
          tahi.setLocation(tahi.getLocation().x, 550); 
          JOptionPane.showMessageDialog(null, "Has logrado salir del\n'Jardín de las Fuentes'\ncon la Gema Azul en tu poder ...", "Mensaje",1, new ImageIcon (getClass().getResource("imagenes/barra/recursos/recurso6.png"))); 
          GestorJuego.getInstance().agregarRecurso(6);
          
          tahi.setIcon(corriendo);          
          while(tahi.getY() > 160)
          { 
              tahi.setLocation(tahi.getX(),tahi.getY()-2);
              try { Thread.sleep(20); } catch (InterruptedException ex) {}          
          }  
          
          tahi.setIcon(detenido);
          try { Thread.sleep(3000); } catch (InterruptedException ex) {} 
          
          tahi.setIcon(corriendo);          
          while(tahi.getY() > -100)
          { 
              tahi.setLocation(tahi.getX(),tahi.getY()-2);
              try { Thread.sleep(20); } catch (InterruptedException ex) {}          
          }
          
          try { Thread.sleep(2000); } catch (InterruptedException ex) {}
          cerrarVentana();
       }
    }

}
