/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Jonathan
 */
public class TablaPuntaje extends javax.swing.JFrame {
    
    /**
     * Creates new form TablaPuntaje
     */
    public TablaPuntaje() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
        
        JLabel tablero[][] = {{ P1, user1, per1, pun1 },
                              { P2, user2, per2, pun2 },
                              { P3, user3, per3, pun3 },
                              { P4, user4, per4, pun4 },
                              { P5, user5, per5, pun5 }};
        
        ArrayList<Usuario> usuarios = null;
        
        if(GestorJuego.getInstance().getUbicacionBD() == 0)
        { 
          AdministradorConsultasSQL ad = new AdministradorConsultasSQL();
          usuarios = ad.consultarTop();
        } 
        
        if(GestorJuego.getInstance().getUbicacionBD() == 1)
        {
           AdministradorBDLocal adL = new AdministradorBDLocal(); 
           usuarios = adL.consultarTop();           
        }
       
        for(int i=0; i<usuarios.size(); i++)
        {
          (tablero[i][0]).setText(""+(i+1)); 
          (tablero[i][1]).setText(usuarios.get(i).getNickName());
          (tablero[i][2]).setText(usuarios.get(i).getGenero());
          (tablero[i][3]).setText(usuarios.get(i).getPuntaje());
          
          if(GestorJuego.getInstance().getUsuario().equals((tablero[i][1]).getText()))
          {             
             (tablero[i][1]).setForeground(Color.cyan);
             (tablero[i][2]).setForeground(Color.cyan);
             (tablero[i][3]).setForeground(Color.cyan);
          }
        } 
        
        switch(GestorJuego.getInstance().getUbicacionBD())
        {
            case 0: baseDeDatos.setText("");
            case 1: baseDeDatos.setText("BD Local");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        gaviotas = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        gaviotas1 = new javax.swing.JLabel();
        continuar = new javax.swing.JLabel();
        nota1 = new javax.swing.JLabel();
        P0 = new javax.swing.JLabel();
        user0 = new javax.swing.JLabel();
        per0 = new javax.swing.JLabel();
        pun0 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        P5 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        per1 = new javax.swing.JLabel();
        per2 = new javax.swing.JLabel();
        per3 = new javax.swing.JLabel();
        per4 = new javax.swing.JLabel();
        per5 = new javax.swing.JLabel();
        pun1 = new javax.swing.JLabel();
        pun2 = new javax.swing.JLabel();
        pun3 = new javax.swing.JLabel();
        pun4 = new javax.swing.JLabel();
        pun5 = new javax.swing.JLabel();
        fondocuadro = new javax.swing.JLabel();
        baseDeDatos = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iZafiro - Mejores Jugadores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/iZafito-Tittle-80.png"))); // NOI18N
        titulo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 17, -1, 42));

        gaviotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(gaviotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 63));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/iZafito-Tittle-80.png"))); // NOI18N
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 59, -1, 60));

        gaviotas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/gabiotas.gif"))); // NOI18N
        gaviotas1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(gaviotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        continuar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        continuar.setForeground(new java.awt.Color(255, 255, 255));
        continuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continuar.setText("Continuar");
        continuar.setPreferredSize(new java.awt.Dimension(90, 40));
        continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continuarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continuarMouseEntered(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        nota1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nota1.setForeground(new java.awt.Color(255, 255, 255));
        nota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota1.setText("Estos son los 5 mejores puntajes. ¡Anímate a estar en esta lista!");
        getContentPane().add(nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 638, -1));

        P0.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        P0.setForeground(java.awt.Color.cyan);
        P0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P0.setText("#");
        getContentPane().add(P0, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 165, 48, 20));

        user0.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        user0.setForeground(java.awt.Color.cyan);
        user0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user0.setText("Usuario");
        getContentPane().add(user0, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 165, 138, 20));

        per0.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        per0.setForeground(java.awt.Color.cyan);
        per0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        per0.setText("Personaje");
        getContentPane().add(per0, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 165, 108, 20));

        pun0.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pun0.setForeground(java.awt.Color.cyan);
        pun0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pun0.setText("Puntaje");
        getContentPane().add(pun0, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 165, 58, 20));

        P1.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        P1.setForeground(java.awt.Color.cyan);
        P1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 50, 20));

        P2.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        P2.setForeground(java.awt.Color.cyan);
        P2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 209, 50, 20));

        P3.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        P3.setForeground(java.awt.Color.cyan);
        P3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 228, 50, 20));

        P4.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        P4.setForeground(java.awt.Color.cyan);
        P4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 247, 50, 20));

        P5.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        P5.setForeground(java.awt.Color.cyan);
        P5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(P5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 266, 50, 20));

        user1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 20));

        user2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 209, 140, 20));

        user3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        user3.setForeground(new java.awt.Color(255, 255, 255));
        user3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(user3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 228, 140, 20));

        user4.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        user4.setForeground(new java.awt.Color(255, 255, 255));
        user4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(user4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, 140, 20));

        user5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        user5.setForeground(new java.awt.Color(255, 255, 255));
        user5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(user5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 266, 140, 20));

        per1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        per1.setForeground(new java.awt.Color(255, 255, 255));
        per1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        per1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(per1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 110, 20));

        per2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        per2.setForeground(new java.awt.Color(255, 255, 255));
        per2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        per2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(per2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 209, 110, 20));

        per3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        per3.setForeground(new java.awt.Color(255, 255, 255));
        per3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        per3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(per3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 228, 110, 20));

        per4.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        per4.setForeground(new java.awt.Color(255, 255, 255));
        per4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        per4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(per4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 247, 110, 20));

        per5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        per5.setForeground(new java.awt.Color(255, 255, 255));
        per5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        per5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(per5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 266, 110, 20));

        pun1.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        pun1.setForeground(new java.awt.Color(255, 255, 255));
        pun1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pun1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(pun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 60, 20));

        pun2.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        pun2.setForeground(new java.awt.Color(255, 255, 255));
        pun2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pun2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(pun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 209, 60, 20));

        pun3.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        pun3.setForeground(new java.awt.Color(255, 255, 255));
        pun3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pun3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(pun3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 228, 60, 20));

        pun4.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        pun4.setForeground(new java.awt.Color(255, 255, 255));
        pun4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pun4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(pun4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 247, 60, 20));

        pun5.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        pun5.setForeground(new java.awt.Color(255, 255, 255));
        pun5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pun5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(pun5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 266, 60, 20));

        fondocuadro.setForeground(new java.awt.Color(255, 255, 255));
        fondocuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/creditos/efectodescripcion/fondocreditosmusica.png"))); // NOI18N
        fondocuadro.setText("Hola");
        fondocuadro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fondocuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(fondocuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 125, 520, 180));

        baseDeDatos.setForeground(new java.awt.Color(0, 202, 202));
        baseDeDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baseDeDatos.setText("BD Local");
        getContentPane().add(baseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/fondoportada.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseClicked
        // TODO add your handling code here:
        Sonidos.getInstance().detener("portada");
        Sonidos.getInstance().detener("sonidosbosque");
        Sonidos.getInstance().detener("creditos");
        
        setVisible(false);
        dispose();
        
        new CargadorEscenarios1().setVisible(true);
    }//GEN-LAST:event_continuarMouseClicked

    private void continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseExited
        // TODO add your handling code here:
        continuar.setForeground(Color.white);
    }//GEN-LAST:event_continuarMouseExited

    private void continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseEntered
        // TODO add your handling code here:
        continuar.setForeground(Color.cyan);
        Sonidos.getInstance().reproducir("boton");
    }//GEN-LAST:event_continuarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            @Override
            public void run() {
                try {
                    new TablaPuntaje().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TablaPuntaje.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P0;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel P5;
    private javax.swing.JLabel baseDeDatos;
    private javax.swing.JLabel continuar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondocuadro;
    private javax.swing.JLabel gaviotas;
    private javax.swing.JLabel gaviotas1;
    private javax.swing.JLabel nota1;
    private javax.swing.JLabel per0;
    private javax.swing.JLabel per1;
    private javax.swing.JLabel per2;
    private javax.swing.JLabel per3;
    private javax.swing.JLabel per4;
    private javax.swing.JLabel per5;
    private javax.swing.JLabel pun0;
    private javax.swing.JLabel pun1;
    private javax.swing.JLabel pun2;
    private javax.swing.JLabel pun3;
    private javax.swing.JLabel pun4;
    private javax.swing.JLabel pun5;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel user0;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    // End of variables declaration//GEN-END:variables


}
