/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package izafiro;

import java.applet.AudioClip;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacc89
 */
public final class Ventana22_s1 extends javax.swing.JFrame {

    AudioClip clip1;
    
    //Variables del cambio de Ventana
    private JFrame[][] vJF;
    private int numVentanaFila ;
    private int numVentanaColm;
    
    // Variables del Movimiento
    private static final int SPEED = GestorJuego.getInstance().getSpeed(); //Velocidad de Tahi
    private static final int FRECUENCIA = GestorJuego.getInstance().getFrecuencia(); //Frecuencia del movimiento de pies de Tahi
    private static final int RADIO = 15; //Distancia para conversar con otros personajes
    private Desplazamiento desplazamiento = Desplazamiento.getInstance(); //Invocador de metodos relacionados con el desplazamiento
    private Deposito d; //Clase deposito que guerada las variables primitivas del JFrame
    
    //Variables de Interaccion con el escenario (obstaculos y conversaciones)
    private ArrayList<Conversador> conversadores;
    private ArrayList<JLabel> obstaculos;
    private Obstaculo obstaculosAbajo;
    private Obstaculo obstaculosIzquierda;
    private Obstaculo obstaculosDerecha;
    private Obstaculo obstaculosArriba;
    private ArrayList<Enemigo> enemigos;
    
    //Variable sobre el estado de Tahi
    GestorJuego t = GestorJuego.getInstance();
    
    
    /**
     * Creates new form Ventana00_s1
     */
    public Ventana22_s1() {
        initComponents();
        this.setLocationRelativeTo(null); this.setIconImage(new ImageIcon (getClass().getResource("izafiroicono.png")).getImage()); Sonidos.getInstance().activarCursor(this);
        this.d = new Deposito(tahi.getX(),tahi.getY(),this);
        cargarObstaculos();
        cargarPersonajes();
        this.addKeyListener(Teclado.getInstace());//ActionListener para deneter la musica de fodndo 
        this.addKeyListener(new Ventana22_s1.AL());//ActionListener para el movimiento del personaje        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numPuntaje1 = new javax.swing.JLabel();
        numPuntaje2 = new javax.swing.JLabel();
        numPuntaje3 = new javax.swing.JLabel();
        numPuntaje4 = new javax.swing.JLabel();
        marcoPuntaje = new javax.swing.JLabel();
        pausa = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();
        ayuda = new javax.swing.JLabel();
        puntaje = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        recurso1 = new javax.swing.JLabel();
        recurso2 = new javax.swing.JLabel();
        recurso3 = new javax.swing.JLabel();
        recurso4 = new javax.swing.JLabel();
        recurso5 = new javax.swing.JLabel();
        recurso6 = new javax.swing.JLabel();
        recursos = new javax.swing.JLabel();
        energia = new javax.swing.JLabel();
        salud = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();
        cuadroDialogo = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        objeto1 = new javax.swing.JLabel();
        objeto2 = new javax.swing.JLabel();
        objeto3 = new javax.swing.JLabel();
        objeto4 = new javax.swing.JLabel();
        objeto5 = new javax.swing.JLabel();
        objeto6 = new javax.swing.JLabel();
        objeto7 = new javax.swing.JLabel();
        objeto8 = new javax.swing.JLabel();
        espadazo = new javax.swing.JLabel();
        ave4 = new javax.swing.JLabel();
        ave3 = new javax.swing.JLabel();
        ave2 = new javax.swing.JLabel();
        ave1 = new javax.swing.JLabel();
        tahi = new javax.swing.JLabel();
        obstaculo1 = new javax.swing.JLabel();
        obstaculo2 = new javax.swing.JLabel();
        obstaculo3 = new javax.swing.JLabel();
        obstaculo4 = new javax.swing.JLabel();
        obstaculo5 = new javax.swing.JLabel();
        obstaculo6 = new javax.swing.JLabel();
        obstaculo7 = new javax.swing.JLabel();
        obstaculo8 = new javax.swing.JLabel();
        obstaculo9 = new javax.swing.JLabel();
        obstaculo10 = new javax.swing.JLabel();
        obstaculo11 = new javax.swing.JLabel();
        obstaculo12 = new javax.swing.JLabel();
        obstaculo13 = new javax.swing.JLabel();
        obstaculo14 = new javax.swing.JLabel();
        obstaculo15 = new javax.swing.JLabel();
        obstaculo16 = new javax.swing.JLabel();
        obstaculo17 = new javax.swing.JLabel();
        obstaculo18 = new javax.swing.JLabel();
        obstaculo19 = new javax.swing.JLabel();
        obstaculo20 = new javax.swing.JLabel();
        obstaculo21 = new javax.swing.JLabel();
        obstaculo22 = new javax.swing.JLabel();
        obstaculo23 = new javax.swing.JLabel();
        obstaculo24 = new javax.swing.JLabel();
        obstaculo26 = new javax.swing.JLabel();
        cerca = new javax.swing.JLabel();
        aldeano4 = new javax.swing.JLabel();
        obstaculoCerca = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iZafiro - Bosque de las Luciérnagas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numPuntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numPuntaje1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numerospuntaje/0.png"))); // NOI18N
        getContentPane().add(numPuntaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 35, 14, 29));
        numPuntaje1.getAccessibleContext().setAccessibleName("numPuntaje1");

        numPuntaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numPuntaje2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numerospuntaje/0.png"))); // NOI18N
        getContentPane().add(numPuntaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 35, 14, 29));
        numPuntaje2.getAccessibleContext().setAccessibleName("numPuntaje2");

        numPuntaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numPuntaje3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numerospuntaje/0.png"))); // NOI18N
        getContentPane().add(numPuntaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 35, 14, 29));
        numPuntaje3.getAccessibleContext().setAccessibleName("numPuntaje3");

        numPuntaje4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numPuntaje4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numerospuntaje/0.png"))); // NOI18N
        getContentPane().add(numPuntaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 35, 14, 29));
        numPuntaje4.getAccessibleContext().setAccessibleName("numPuntaje4");

        marcoPuntaje.setBackground(new java.awt.Color(239, 255, 239));
        marcoPuntaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        marcoPuntaje.setOpaque(true);
        getContentPane().add(marcoPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 30, 70, 35));

        pausa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        pausa.setForeground(new java.awt.Color(255, 255, 255));
        pausa.setText("Pausa: Tecla P");
        getContentPane().add(pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        sound.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sound.setForeground(new java.awt.Color(255, 255, 255));
        sound.setText("On/Off Música: Tecla S");
        getContentPane().add(sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 30, -1, -1));

        ayuda.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText("Ayuda: Tecla A");
        getContentPane().add(ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        puntaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        puntaje.setForeground(new java.awt.Color(255, 255, 255));
        puntaje.setText("Puntaje");
        getContentPane().add(puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/izafitotittlepequeno.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        recurso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos/recurso0.png"))); // NOI18N
        getContentPane().add(recurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 515, 28, 28));
        recurso1.getAccessibleContext().setAccessibleName("recurso1");

        recurso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos/recurso0.png"))); // NOI18N
        getContentPane().add(recurso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 515, 28, 28));
        recurso2.getAccessibleContext().setAccessibleName("recurso2");

        recurso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos/recurso0.png"))); // NOI18N
        getContentPane().add(recurso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 515, 28, 28));
        recurso3.getAccessibleContext().setAccessibleName("recurso3");

        recurso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos/recurso0.png"))); // NOI18N
        getContentPane().add(recurso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 550, 28, 28));
        recurso4.getAccessibleContext().setAccessibleName("recurso4");

        recurso5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos/recurso0.png"))); // NOI18N
        getContentPane().add(recurso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 550, 28, 28));
        recurso5.getAccessibleContext().setAccessibleName("recurso5");

        recurso6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos/recurso0.png"))); // NOI18N
        getContentPane().add(recurso6, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 550, 28, 28));
        recurso6.getAccessibleContext().setAccessibleName("recurso6");

        recursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/recursos.png"))); // NOI18N
        getContentPane().add(recursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 508, -1, -1));

        energia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        energia.setForeground(new java.awt.Color(255, 255, 255));
        energia.setText("Salud");
        getContentPane().add(energia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));
        energia.getAccessibleContext().setAccessibleName("");

        salud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/salud5.PNG"))); // NOI18N
        getContentPane().add(salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));
        salud.getAccessibleContext().setAccessibleName("salud");

        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numeros/-.png"))); // NOI18N
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 535, 14, 29));
        n1.getAccessibleContext().setAccessibleName("n1");

        n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numeros/-.png"))); // NOI18N
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 535, 14, 29));
        n2.getAccessibleContext().setAccessibleName("n2");

        n3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numeros/-.png"))); // NOI18N
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 535, 14, 29));
        n3.getAccessibleContext().setAccessibleName("n3");

        n4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra/numeros/-.png"))); // NOI18N
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 535, 14, 29));
        n4.getAccessibleContext().setAccessibleName("n4");

        hora.setBackground(new java.awt.Color(0, 0, 0));
        hora.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        hora.setForeground(new java.awt.Color(204, 0, 0));
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText(":");
        hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        hora.setOpaque(true);
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 100, 40));
        hora.getAccessibleContext().setAccessibleName("hora");

        barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/barra.png"))); // NOI18N
        barra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        barra.setMaximumSize(new java.awt.Dimension(800, 110));
        barra.setMinimumSize(new java.awt.Dimension(800, 110));
        barra.setPreferredSize(new java.awt.Dimension(800, 110));
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        cuadroDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/dialogos/escenario1/ventana[0,2]/conversador1/dialogo1/1.png"))); // NOI18N
        getContentPane().add(cuadroDialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 0, 0));

        tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/tiempo/dia1.png"))); // NOI18N
        getContentPane().add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));
        tiempo.getAccessibleContext().setAccessibleName("tiempo");

        objeto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        objeto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/arbol5.png"))); // NOI18N
        objeto1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(objeto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 130, 150));

        objeto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/espantapajaros.png"))); // NOI18N
        getContentPane().add(objeto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 109, -1, -1));

        objeto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/espantapajaros.png"))); // NOI18N
        getContentPane().add(objeto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 140, -1, -1));

        objeto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/techo1.png"))); // NOI18N
        getContentPane().add(objeto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 294, -1, -1));

        objeto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/techo1.png"))); // NOI18N
        getContentPane().add(objeto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 342, -1, -1));

        objeto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/techo2.png"))); // NOI18N
        getContentPane().add(objeto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 283, -1, -1));

        objeto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/tendedero.png"))); // NOI18N
        objeto7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(objeto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 198, -1, 40));

        objeto8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(objeto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 238, 20, 20));

        espadazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espadazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/espadazo.gif"))); // NOI18N
        getContentPane().add(espadazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -21, 0, 0));

        ave4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/personajes/ave/ave1.gif"))); // NOI18N
        getContentPane().add(ave4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        ave3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/personajes/ave/ave1.gif"))); // NOI18N
        getContentPane().add(ave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        ave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/personajes/ave/ave1.gif"))); // NOI18N
        getContentPane().add(ave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        ave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/personajes/ave/ave1.gif"))); // NOI18N
        getContentPane().add(ave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        tahi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/personajes/tahi/tahi2.png"))); // NOI18N
        getContentPane().add(tahi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));
        tahi.getAccessibleContext().setAccessibleName("tahi");

        getContentPane().add(obstaculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 0, 24, 210));
        getContentPane().add(obstaculo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 80, 8));
        getContentPane().add(obstaculo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 312, 25, 180));
        getContentPane().add(obstaculo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 370, 160, 120));
        getContentPane().add(obstaculo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 160, 70));
        getContentPane().add(obstaculo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 360, 160, 130));
        getContentPane().add(obstaculo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 473, 70, 20));
        getContentPane().add(obstaculo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 25, 260));
        getContentPane().add(obstaculo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 396, 30, 90));
        getContentPane().add(obstaculo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 489, 500, -1));
        getContentPane().add(obstaculo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 0, 145, 75));
        getContentPane().add(obstaculo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 448, 30, 40));
        getContentPane().add(obstaculo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 0, 115));
        getContentPane().add(obstaculo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, -1, 110, 10));
        getContentPane().add(obstaculo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, 341, 110));
        getContentPane().add(obstaculo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 57, 60, 0));
        getContentPane().add(obstaculo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 140, 50, 10));
        getContentPane().add(obstaculo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 20, 0, 130));
        getContentPane().add(obstaculo19, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 29, 100, 10));
        getContentPane().add(obstaculo20, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 143, 50, 8));
        getContentPane().add(obstaculo21, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 147, 15, -1));
        getContentPane().add(obstaculo22, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 179, 15, -1));
        getContentPane().add(obstaculo23, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 235, 110, 5));
        getContentPane().add(obstaculo24, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 168, 20, 20));
        getContentPane().add(obstaculo26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 58, 680, 360));

        cerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/objetos/cerca.png"))); // NOI18N
        getContentPane().add(cerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 208, 0, 0));
        getContentPane().add(aldeano4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 30, 20));
        getContentPane().add(obstaculoCerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 208, 10, 110));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izafiro/imagenes/escenarios/escenario1/v22.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana22_s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana22_s1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aldeano4;
    private javax.swing.JLabel ave1;
    private javax.swing.JLabel ave2;
    private javax.swing.JLabel ave3;
    private javax.swing.JLabel ave4;
    private javax.swing.JLabel ayuda;
    private javax.swing.JLabel barra;
    private javax.swing.JLabel cerca;
    private javax.swing.JLabel cuadroDialogo;
    private javax.swing.JLabel energia;
    private javax.swing.JLabel espadazo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel marcoPuntaje;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel numPuntaje1;
    private javax.swing.JLabel numPuntaje2;
    private javax.swing.JLabel numPuntaje3;
    private javax.swing.JLabel numPuntaje4;
    private javax.swing.JLabel objeto1;
    private javax.swing.JLabel objeto2;
    private javax.swing.JLabel objeto3;
    private javax.swing.JLabel objeto4;
    private javax.swing.JLabel objeto5;
    private javax.swing.JLabel objeto6;
    private javax.swing.JLabel objeto7;
    private javax.swing.JLabel objeto8;
    private javax.swing.JLabel obstaculo1;
    private javax.swing.JLabel obstaculo10;
    private javax.swing.JLabel obstaculo11;
    private javax.swing.JLabel obstaculo12;
    private javax.swing.JLabel obstaculo13;
    private javax.swing.JLabel obstaculo14;
    private javax.swing.JLabel obstaculo15;
    private javax.swing.JLabel obstaculo16;
    private javax.swing.JLabel obstaculo17;
    private javax.swing.JLabel obstaculo18;
    private javax.swing.JLabel obstaculo19;
    private javax.swing.JLabel obstaculo2;
    private javax.swing.JLabel obstaculo20;
    private javax.swing.JLabel obstaculo21;
    private javax.swing.JLabel obstaculo22;
    private javax.swing.JLabel obstaculo23;
    private javax.swing.JLabel obstaculo24;
    private javax.swing.JLabel obstaculo26;
    private javax.swing.JLabel obstaculo3;
    private javax.swing.JLabel obstaculo4;
    private javax.swing.JLabel obstaculo5;
    private javax.swing.JLabel obstaculo6;
    private javax.swing.JLabel obstaculo7;
    private javax.swing.JLabel obstaculo8;
    private javax.swing.JLabel obstaculo9;
    private javax.swing.JLabel obstaculoCerca;
    private javax.swing.JLabel pausa;
    private javax.swing.JLabel puntaje;
    private javax.swing.JLabel recurso1;
    private javax.swing.JLabel recurso2;
    private javax.swing.JLabel recurso3;
    private javax.swing.JLabel recurso4;
    private javax.swing.JLabel recurso5;
    private javax.swing.JLabel recurso6;
    private javax.swing.JLabel recursos;
    private javax.swing.JLabel salud;
    private javax.swing.JLabel sound;
    private javax.swing.JLabel tahi;
    private javax.swing.JLabel tiempo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the vJF
     */
    public JFrame[][] getvJF() {
        return vJF;
    }

    /**
     * @param vJF the vJF to set
     */
    public void setvJF(JFrame[][] vJF) {
        this.vJF = vJF;
    }

    /**
     * @return the numVentanaFila
     */
    public int getNumVentanaFila() {
        return numVentanaFila;
    }

    /**
     * @param numVentanaFila the numVentanaFila to set
     */
    public void setNumVentanaFila(int numVentanaFila) {
        this.numVentanaFila = numVentanaFila;
    }


    void setPosicionVentana(int fila, int columna) {
        this.numVentanaFila = fila;
        this.setNumVentanaColm(columna);
    }

    /**
     * @return the numVentanaColm
     */
    public int getNumVentanaColm() {
        return numVentanaColm;
    }

    /**
     * @param numVentanaColm the numVentanaColm to set
     */
    public void setNumVentanaColm(int numVentanaColm) {
        this.numVentanaColm = numVentanaColm;
    }

    private void cargarPersonajes() {
        
       conversadores = new ArrayList<>();       
       enemigos = new ArrayList<>(); 
       
       
       //Se agregan los diferentes dialogos de conversador 1 (aldeano).
      
      ArrayList<Conversacion>conversaciones1 = new ArrayList<>();
        
        Conversacion dialogo0 = new Conversacion();
                
        dialogo0.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador1/dialogo1/1.png")));      
        dialogo0.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador1/dialogo1/2.png")));
        conversaciones1.add(dialogo0);
       
      Conversador conversador1 = new Conversador(0,obstaculo17,conversaciones1);
      
      
      //Se agregan los diferentes dialogos de conversador 2 (aldeano).
      
      ArrayList<Conversacion>conversaciones2 = new ArrayList<>();
        
        Conversacion dialogo1 = new Conversacion();
                
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/1.png")));      
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/2.png")));
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/3.png")));
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/4.png")));
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/5.png")));
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/6.png")));
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/7.png")));
        dialogo1.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo1/8.png")));
        
        Conversacion dialogo11 = new Conversacion();
                
        dialogo11.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo2/1.png")));      
        dialogo11.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo2/2.png")));
        
        Conversacion dialogo12 = new Conversacion();                
        dialogo12.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador2/dialogo3/1.png")));      
        
        if(GestorJuego.getInstance().getRecursos()[0] && GestorJuego.getInstance().getRecursos()[2] 
           || GestorJuego.getInstance().getMsnApertura()[7])
        {}
        else{
          conversaciones2.add(dialogo1);
          conversaciones2.add(dialogo11);
        }
        conversaciones2.add(dialogo12);
       
      Conversador conversador2 = new Conversador(0,obstaculo24,conversaciones2);
      
      
      //Se agregan los diferentes dialogos de conversador 3 (aldeano).
      
      ArrayList<Conversacion>conversaciones3 = new ArrayList<>();
        
        Conversacion dialogo2 = new Conversacion();
                
        dialogo2.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador3/dialogo1/1.png")));      
        dialogo2.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador3/dialogo1/2.png")));
        conversaciones3.add(dialogo2);
       
      Conversador conversador3 = new Conversador(0,objeto8,conversaciones3);
       
       
       //Se agregan los diferentes dialogos de conversador 4 (aldeano).
      
      ArrayList<Conversacion>conversaciones4 = new ArrayList<>();
        
        Conversacion dialogo4 = new Conversacion();
                
        dialogo4.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador4/dialogo1/1.png")));      
        dialogo4.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[2,2]/conversador4/dialogo1/2.png")));
        conversaciones4.add(dialogo4);
       
      Conversador conversador4 = new Conversador(0,aldeano4,conversaciones4);
       
       //Se agregan los diferentes dialogos o movimientos de conversador (ave).
               
       Conversador conversador5 = new Conversador(0,ave1,null);
       conversador5.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave1.gif")));
       conversador5.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave2.gif")));
       conversador5.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave3.gif")));
       conversador5.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave4.gif")));
       
       //Se agregan los diferentes dialogos o movimientos de conversador (ave).
               
       Conversador conversador6 = new Conversador(0,ave2,null);
       conversador6.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave1.gif")));
       conversador6.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave2.gif")));
       conversador6.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave3.gif")));
       conversador6.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave4.gif")));
       
       //Se agregan los diferentes dialogos o movimientos de conversador (ave).
               
       Conversador conversador7 = new Conversador(0,ave3,null);
       conversador7.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave1.gif")));
       conversador7.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave2.gif")));
       conversador7.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave3.gif")));
       conversador7.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave4.gif")));
       
       //Se agregan los diferentes dialogos o movimientos de conversador (ave).
               
       Conversador conversador8 = new Conversador(0,ave4,null);
       conversador8.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave1.gif")));
       conversador8.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave2.gif")));
       conversador8.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave3.gif")));
       conversador8.getPosiciones().add(new ImageIcon(getClass().getResource("imagenes/personajes/ave/ave4.gif")));
       
       
       //Se agregan los diferentes dialogos de conversador 2 (reja).
      
      ArrayList<Conversacion>conversaciones5 = new ArrayList<>();
      
      Conversacion dialogo5 = new Conversacion();                
      dialogo5.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[0,0]/conversador2/dialogo1/1.png")));
      
      Conversacion dialogo6 = new Conversacion();                
      dialogo6.getMensajes2().add(new ImageIcon (getClass().getResource("imagenes/dialogos/escenario1/ventana[0,0]/conversador2/dialogo2/1.png")));
      
      conversaciones5.add(dialogo5);
      conversaciones5.add(dialogo6);
      
      Conversador conversador9 = new Conversador(0,obstaculoCerca,conversaciones5);
       
       
       conversadores.add(conversador1);
       conversadores.add(conversador2);
       conversadores.add(conversador3);
       conversadores.add(conversador4);
       conversadores.add(conversador5);
       conversadores.add(conversador6);
       conversadores.add(conversador7);
       conversadores.add(conversador8);
       conversadores.add(conversador9);
       
       //Copia de las lista de obstaculos los cuales serán validados por los enemigos
       Obstaculo obsAba = new Obstaculo(); obsAba.setLineas((ArrayList<Linea>)obstaculosAbajo.getLineas().clone());
       Obstaculo obsArr = new Obstaculo(); obsArr.setLineas((ArrayList<Linea>)obstaculosArriba.getLineas().clone());
       Obstaculo obsDer = new Obstaculo(); obsDer.setLineas((ArrayList<Linea>)obstaculosDerecha.getLineas().clone());
       Obstaculo obsIzq = new Obstaculo(); obsIzq.setLineas((ArrayList<Linea>)obstaculosIzquierda.getLineas().clone());
       
       JLabel o = obstaculo26;  //Obstaculo que delimita a los enemigos, no a Tahi. 
       
       int p1 = o.getX();
       int p2 = o.getY();
       int p3 = o.getX()+o.getWidth();
       int p4 = o.getY()+o.getHeight(); 
       
       obsArr.getLineas().add(new Linea(p1,p2,p3,p2,SPEED)); //Obstaculo hacia Abajo...
       obsDer.getLineas().add(new Linea(p3,p2,p3,p4,SPEED)); //Obstaculo a la Izquierda...
       obsIzq.getLineas().add(new Linea(p1,p2,p1,p4,SPEED)); //Obstaculo a la Derecha...
       obsAba.getLineas().add(new Linea(p1,p4,p3,p4,SPEED)); //Obstaculo hacia Arriba...
       
       new Animal(this,conversador5,d,desplazamiento,obsAba,obsArr,obsIzq,obsDer,SPEED,70,tahi).start();
       new Animal(this,conversador6,d,desplazamiento,obsAba,obsArr,obsIzq,obsDer,SPEED,70,tahi).start();
       new Animal(this,conversador7,d,desplazamiento,obsAba,obsArr,obsIzq,obsDer,SPEED,70,tahi).start();
       new Animal(this,conversador8,d,desplazamiento,obsAba,obsArr,obsIzq,obsDer,SPEED,70,tahi).start();
    }

    private void cargarObstaculos() {
        
        int p1;
        int p2;
        int p3;
        int p4;  
        
        this.obstaculos = new ArrayList<>();
        this.obstaculosAbajo = new Obstaculo();
        this.obstaculosIzquierda = new Obstaculo();
        this.obstaculosDerecha = new Obstaculo();
        this.obstaculosArriba = new Obstaculo();
        
        //------------ Definicion de los obstaculos del escenario --------------
        
        if(!GestorJuego.getInstance().getPuertas()[1]){this.obstaculos.add(this.obstaculoCerca); }
        
        this.obstaculos.add(this.obstaculo1);
        this.obstaculos.add(this.obstaculo2);
        this.obstaculos.add(this.obstaculo3);
        this.obstaculos.add(this.obstaculo4);
        this.obstaculos.add(this.obstaculo5);
        this.obstaculos.add(this.obstaculo6);
        this.obstaculos.add(this.obstaculo7);
        this.obstaculos.add(this.obstaculo8);
        this.obstaculos.add(this.obstaculo9);
        this.obstaculos.add(this.obstaculo10);
        this.obstaculos.add(this.obstaculo11);
        this.obstaculos.add(this.obstaculo12);
        this.obstaculos.add(this.obstaculo13);
        this.obstaculos.add(this.obstaculo14);
        this.obstaculos.add(this.obstaculo15);
        this.obstaculos.add(this.obstaculo16);
        this.obstaculos.add(this.obstaculo17);
        this.obstaculos.add(this.obstaculo18);
        this.obstaculos.add(this.obstaculo19);
        this.obstaculos.add(this.obstaculo20);
        this.obstaculos.add(this.obstaculo21);
        this.obstaculos.add(this.obstaculo22);
        this.obstaculos.add(this.obstaculo23);
        this.obstaculos.add(this.obstaculo24);   
        
        //----------------------------------------------------------------------
        
        for(int i = 0; i<this.obstaculos.size(); i++)
        {
           p1 = this.obstaculos.get(i).getX();
           p2 = this.obstaculos.get(i).getY();
           p3 = this.obstaculos.get(i).getX()+this.obstaculos.get(i).getWidth();
           p4 = this.obstaculos.get(i).getY()+this.obstaculos.get(i).getHeight();           
            
           this.obstaculosAbajo.getLineas().add(new Linea(p1,p2,p3,p2,SPEED)); //Obstaculos hacia Abajo...
           this.obstaculosIzquierda.getLineas().add(new Linea(p3,p2,p3,p4,SPEED)); //Obstaculos a la Izquierda...
           this.obstaculosDerecha.getLineas().add(new Linea(p1,p2,p1,p4,SPEED)); //Obstaculos a la Derecha...
           this.obstaculosArriba.getLineas().add(new Linea(p1,p4,p3,p4,SPEED)); //Obstaculos hacia Arriba...                   
        }  
    }
    
    
    public boolean validarPosicionConversadora()
    {
        int x1 = tahi.getX();
        int y1 = tahi.getY();
        int x2 = tahi.getX() + tahi.getWidth();
        int y2 = tahi.getY() + tahi.getHeight(); 
        
        
        for(int i = 0; i<this.conversadores.size(); i++)
        {
          if(this.conversadores.get(i).getDialogos() != null && conversadores.get(i).getImagen() != null)
          {            
           int limiteArriba = conversadores.get(i).getImagen().getY()-RADIO;
           int limiteDerecha = conversadores.get(i).getImagen().getX()+conversadores.get(i).getImagen().getWidth()+RADIO;
           int limiteIzquierda = conversadores.get(i).getImagen().getX()-RADIO;
           int limiteAbajo = conversadores.get(i).getImagen().getY()+conversadores.get(i).getImagen().getHeight()+RADIO;
           
           if( x1 > limiteIzquierda && x1 < limiteDerecha && y1 > limiteArriba && y1 < limiteAbajo )
           { 
              //buscar mensaje.
               d.setNumConv(i); 
               imprimirMensaje(conversadores.get(i));
               return true;
           }
           else
           {
             if( x2 > limiteIzquierda && x2 < limiteDerecha && y1 > limiteArriba && y1 < limiteAbajo )
             {
                //buscar mensaje. 
                d.setNumConv(i);  
                imprimirMensaje(conversadores.get(i));
                return true;
             }
             else
             {
                if( x1 > limiteIzquierda && x1 < limiteDerecha && y2 > limiteArriba && y2 < limiteAbajo )
                {
                   //buscar mensaje.
                   d.setNumConv(i); 
                   imprimirMensaje(conversadores.get(i));
                   return true;
                }
                else
                {
                   if( x2 > limiteIzquierda && x2 < limiteDerecha && y2 > limiteArriba && y2 < limiteAbajo )
                   {
                      //buscar mensaje. 
                      d.setNumConv(i); 
                      imprimirMensaje(conversadores.get(i));                       
                      return true;
                   }    
                }
             }
           }
         }
        }
        return false;
    }
    
    
    public void imprimirMensaje(Conversador c)
    {  
       if(c.getMensajeActual() == 0)
       {
         cuadroDialogo.setSize(cuadroDialogo.getPreferredSize());
       }
       this.cuadroDialogo.setIcon(c.getDialogos().get(c.getDialogoActual()).getMensajes2().get(c.getMensajeActual()));
              
       if(c.getMensajeActual() < c.getDialogos().get(c.getDialogoActual()).getMensajes2().size()-1)
       {
         c.setMensajeActual(c.getMensajeActual()+1); 
         d.setUltimoMensaje(false);
       }
       else
       {
         if(c.getDialogoActual() < c.getDialogos().size()-1)
         {
            if(cuadroDialogo.getIcon().toString().contains("conversador2/dialogo1/1.png")) 
            {                
              if(GestorJuego.getInstance().getRecursos()[2]){//Se pregunta si el personaje tiene la llave.                 
                 c.setDialogoActual(c.getDialogoActual()+1);
              }
              else
              {
                Sonidos.getInstance().reproducir("error");
              }
            }
            else{
              c.setDialogoActual(c.getDialogoActual()+1);
            } 
         }
         c.setMensajeActual(0);
         d.setUltimoMensaje(true);
       }
       if(cuadroDialogo.getIcon().toString().contains("conversador2/dialogo2/1.png") && GestorJuego.getInstance().getRecursos()[2])
       {
           obstaculosArriba.quitarObstaculo(obstaculoCerca, obstaculosArriba, obstaculosAbajo, obstaculosDerecha, obstaculosIzquierda, SPEED); //se abre la rejilla!
           cerca.setSize(0,0);
           GestorJuego.getInstance().abrirPuerta(1);
           GestorJuego.getInstance().quitarRecurso(3);
           //c.setDialogoActual(c.getDialogoActual()+1);
       }
    }
    
    
    public void mensajeApertura() //Hablan Tahi o Lily luego de haber aterrizado!
    {
       d.setVentanaAbierta(true);        
       imprimirMensaje(conversadores.get(0));
    }
    
    
    public class AL extends KeyAdapter
    {       
        
        @Override
        public void keyPressed(KeyEvent e)
        {
            int keyCode = e.getKeyCode();   
            
            if(!GestorJuego.getInstance().getPuertas()[1]){cerca.setSize(cerca.getPreferredSize());}
            
            switch(keyCode)
            {
                case (KeyEvent.VK_DOWN): if(!desplazamiento.obstaculoAba(tahi, obstaculosAbajo) && !d.isVentanaAbierta())//Se valida si hay obstaculo
                                         {
                                            tahi.setLocation(tahi.getX(),tahi.getY()+SPEED);
                                         }
                                         desplazamiento.avanzar(tahi, 1, 3, FRECUENCIA, d); //Movimiento de los pies
                                         if(tahi.getY() > fondo.getHeight()-5)  //Se valida si tahi sale de la ventana
                                         {
                                            desplazamiento.cambiarPantalla(GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],GestorJuego.getInstance().getvJF()[getNumVentanaFila()+1][getNumVentanaColm()],tahi,tahi.getX(),0,SPEED);                                            
                                         }
                                         break;
                    
                case (KeyEvent.VK_RIGHT): if(!desplazamiento.obstaculoDer(tahi, obstaculosDerecha) && !d.isVentanaAbierta())//Se valida si hay obstaculo
                                          {
                                            tahi.setLocation(tahi.getX()+SPEED,tahi.getY());
                                          }  
                                          desplazamiento.avanzar(tahi, 7, 9, FRECUENCIA, d); //Movimiento de los pies
                                          if(tahi.getX() > fondo.getWidth()-5) //Se valida si tahi sale de la ventana
                                          {                                                      
                                            desplazamiento.cambiarPantalla(GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()+1],tahi,0,tahi.getY(),SPEED);    
                                          }
                                          break;  
                    
                case (KeyEvent.VK_UP): if(!desplazamiento.obstaculoArr(tahi, obstaculosArriba) && !d.isVentanaAbierta())//Se valida si hay obstaculo
                                       {
                                         tahi.setLocation(tahi.getX(),tahi.getY()-SPEED);
                                       } 
                                       desplazamiento.avanzar(tahi, 10, 12, FRECUENCIA, d); //Movimiento de los pies
                                       if(tahi.getY()+tahi.getHeight() < 5) //Se valida si tahi sale de la ventana
                                       {
                                          desplazamiento.cambiarPantalla(GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],GestorJuego.getInstance().getvJF()[getNumVentanaFila()-1][getNumVentanaColm()],tahi,tahi.getX(),fondo.getHeight()-tahi.getHeight(),SPEED);    
                                       }
                                       break;
                    
                case (KeyEvent.VK_LEFT): if(!desplazamiento.obstaculoIzq(tahi, obstaculosIzquierda) && !d.isVentanaAbierta())//Se valida si hay obstaculo
                                         {
                                           tahi.setLocation(tahi.getX()-SPEED,tahi.getY());
                                         }
                                         desplazamiento.avanzar(tahi, 4, 6, FRECUENCIA, d); //Movimiento de los pies
                                         if(tahi.getX()+tahi.getWidth() < 5) //Se valida si tahi sale de la ventana
                                         {
                                            desplazamiento.cambiarPantalla(GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()-1],tahi,fondo.getWidth() - tahi.getWidth(),tahi.getY(),SPEED);    
                                         }
                                         break;
                    
                case (KeyEvent.VK_Y): if(cuadroDialogo.getIcon().toString().contains("conversador1/dialogo1/2"))
                                      {
                                        PruebaPuzzle.getInstance().abrirActividad(3,GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],new Point(tahi.getX(),tahi.getY()));
                                      }
                                      else if(cuadroDialogo.getIcon().toString().contains("conversador2/dialogo3/1"))
                                      {
                                        PruebaPuzzle.getInstance().abrirActividad(4,GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],new Point(tahi.getX(),tahi.getY()));
                                      }
                                      cuadroDialogo.setSize(0,0); 
                                      d.setVentanaAbierta(false);                     
                                      break;
                                       
                case (KeyEvent.VK_N): cuadroDialogo.setSize(0,0); 
                                      d.setVentanaAbierta(false);
                                      break;
                    
                case (KeyEvent.VK_SPACE): if(GestorJuego.getInstance().getRecursos()[0]){new Espadazo(enemigos,espadazo,tahi).start();}                                        
                                          break;
                    
                case (KeyEvent.VK_ENTER): if( !d.isVentanaAbierta() )
                                          {
                                             if(validarPosicionConversadora())
                                             { 
                                                d.setVentanaAbierta(true); 
                                             }
                                          }
                                          else
                                          {
                                             if(d.isUltimoMensaje())
                                             {                                    
                                                cuadroDialogo.setSize(0,0); 
                                                d.setVentanaAbierta(false);
                                                casosEspeciales();
                                             }
                                             else
                                             {
                                               imprimirMensaje(conversadores.get(d.getNumConv()));
                                             }
                                          }
                                          break;
            }
        }
        
        public void casosEspeciales()
        {          
          if(cuadroDialogo.getIcon().toString().contains("conversador2/dialogo1/8")) //se abre por 1ra vez el puzzle
          { 
            PruebaPuzzle.getInstance().abrirActividad(4,GestorJuego.getInstance().getvJF()[getNumVentanaFila()][getNumVentanaColm()],new Point(tahi.getX(),tahi.getY()));
          }
          else if(cuadroDialogo.getIcon().toString().contains("conversador2/dialogo2/2")) //Se le dará la llave
          { 
            GestorJuego.getInstance().agregarRecurso(3); //llave es el recurso No 3.                                   
          }
        }
        
        @Override
        public void keyReleased(KeyEvent e) //Cambio de imagen a estatica sobre Tahi (hacia adelante o hacia atras)
        {
            int keyCode = e.getKeyCode();            
                       
            switch(keyCode)
            {
                case (KeyEvent.VK_DOWN): desplazamiento.detenerse(tahi, 0);break; //Se detiene hacia adelante.     
                case (KeyEvent.VK_UP): desplazamiento.detenerse(tahi, 1);break; //Se detiene hacia atras. 
            }
        }
     }
    
}
